stages:
  - deploy

variables:
    GIT_STRATEGY: clone

deploy:
  tags:
    - shell
  stage: deploy
  only:
    - deploy
  script:
    - docker build --tag=reverse-proxy .
    - (docker stop reverse-proxy && docker rm reverse-proxy) || echo "No old containers detected"
    - docker run --detach --name=reverse-proxy --restart=always --network=host reverse-proxy
    - docker rmi $(docker images -f "dangling=true" -q) || echo "No old images detected"
