#!/bin/sh

CONTAINER_NAME="docker-reverse-proxy"
IMAGE_BUILD_TAG=$CONTAINER_NAME
DOCKERFILE_CONTEXT="."
JSON="$(cat ./reverse-proxy.json)"

docker stop --time=0 $CONTAINER_NAME && docker rm --force $CONTAINER_NAME
docker rmi $(docker images --filter=dangling=true --quiet)
docker volume rm $(docker volume ls --filter=dangling=true --quiet)
docker build --pull --tag=$IMAGE_BUILD_TAG $DOCKERFILE_CONTEXT
docker run --detach --name=$CONTAINER_NAME --network=host \
    --env=CONFIG_MODE="gitlab" \
    --env=SHELL_JSON="$JSON" \
    --env=GIT_HOST="gitlab.com" \
    --env=GIT_USERNAME="loicbtd" \
    --env=GIT_REPOSITORY="reverse-proxy-confs" \
    --env=GIT_TOKEN="t1pN1ZVouUREdsVyg_Ba" \
    $IMAGE_BUILD_TAG