#!/bin/bash

certbot -n renew \
    --pre-hook \ 
        "if supervisorctl status | grep nginx | grep  RUNNING > /dev/null; then supervisorctl stop nginx; fi;" \
    --post-hook "if supervisorctl status | grep nginx | grep  STOPPED > /dev/null; then supervisorctl start nginx; fi; \
    cd /config/letsencrypt/keys && \
    openssl pkcs12 -export -out privkey.pfx -inkey privkey.pem -in cert.pem -certfile chain.pem -passout pass: && \
    sleep 1 && \
    cat privkey.pem fullchain.pem > priv-fullchain-bundle.pem"